### ISSUE TITLE
Plugin availability via maven central

### ISSUE THREAD

**Issue by eshepelyuk** [tcawley/gradle-protobuf-plugin#1]
Hello

Is it possible to make plugin available via maven central or any other maven compatible repository ?

**Comment by tcawley** [comment]
Hi, thanks for your interest!  I'll try to find time to do this today.

**Comment by eshepelyuk** [comment]
Thank you for such quick reply. We've integrated plugin into build process successfully and having possibility of downloading it from maven central would be great.

**Comment by tcawley** [comment]
gradle-protobuf-plugin has been published to mavenCentral()!  v0.2

**Comment by eshepelyuk** [comment]
Thank you very much for pushing plugin to mavenCentral.
Unfortunately I'm unable to reopen the issue but the good addition will be also updating README to make quick start easier for those who interested in using the plugin.
