### ISSUE TITLE
Plans for new release (post 0.2)

### ISSUE THREAD

**Issue by eshepelyuk** [tcawley/gradle-protobuf-plugin#4]
Hi

Do you have in mind releasing new version of the plugin in nearest future ?
We'd really like to start using version form Maven Central with incremental compilation available instead of local jar

Thanks in advance.

**Comment by tcawley** [comment]
I pulled in your changes and pushed out a release to mavenCentral, but left the version as 0.2.

**Comment by eshepelyuk** [comment]
Pulled new version form maven central successfully.
Thank you
